name: build
on:
  push:
    branches: ["main"]

env:
  PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
#  AGENT_VERSION: "1.175.0"

jobs:
  build:
    matrix:
      agent_version:
        - latest
        - 1.402
        - 1.403
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: scheiblingco
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: scheibling
          password: ${{ env.PASSWORD }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            AGENT_VERSION=${{ matrix.agent_version }}
          push: true
          tags: |
            ghcr.io/scheiblingco/windmill-x:${{ matrix.agent_version }}
            docker.io/scheibling/windmill-x:${{ matrix.agent_version }}
